services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    _instanceof:
        App\SharedKernel\CommandHandler\CommandHandlerInterface:
            tags:
              - { name: messenger.message_handler, bus: command.bus }

