doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App/Auth/Domain/Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Domain/Entity'
                prefix: 'App\Auth\Domain\Entity'
                alias: App\Auth\Domain\Entity
            App/Likes/Domain/Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Likes/Domain/Entity'
                prefix: 'App\Likes\Domain\Entity'
                alias: App\Likes\Domain\Entity
            App/Photo/Domain/Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Photo/Domain/Entity'
                prefix: 'App\Photo\Domain\Entity'
                alias: App\Photo\Domain\Entity
            App/User/Domain/Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'
                alias: App\User\Domain\Entity
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
